name: Deploy from main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Add your deploy steps below
      # Example: Deploy to GitHub Pages, FTP, or another hosting provider
